// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SGContrato.Models;

namespace SGContrato.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20191224214437_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("SGContrato.Models.contrato", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("bol_recurrencia");

                    b.Property<DateTime>("dt_fechaFin");

                    b.Property<DateTime>("dt_fechaInicio");

                    b.Property<DateTime>("dt_fechaSuscripcion");

                    b.Property<DateTime>("dt_fechaUltimoCambio");

                    b.Property<int>("qn_proveedor");

                    b.Property<int>("qn_tipoContrato");

                    b.Property<int>("qn_tipoProceso");

                    b.Property<int>("qn_unidadConsolidadora");

                    b.Property<int>("qn_vigenciaContrato");

                    b.Property<string>("txt_nombreAdministrador");

                    b.Property<string>("txt_nombreDelegado");

                    b.Property<string>("txt_nombreTecnicoExterno");

                    b.Property<string>("txt_numProceso");

                    b.Property<string>("txt_objetoContratacion");

                    b.Property<double>("vm_montoAdjudicado");

                    b.HasKey("ID");

                    b.ToTable("contrato");
                });

            modelBuilder.Entity("SGContrato.Models.Seccion", b =>
                {
                    b.Property<int>("seccionID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("txt_detalleSeccion");

                    b.Property<string>("txt_nombreSeccion");

                    b.HasKey("seccionID");

                    b.ToTable("Seccion");
                });

            modelBuilder.Entity("SGContrato.Models.Tipo", b =>
                {
                    b.Property<int>("tipoID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("seccionId");

                    b.Property<string>("txt_detalleTipo");

                    b.Property<string>("txt_nombreTipo");

                    b.HasKey("tipoID");

                    b.HasIndex("seccionId");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("SGContrato.Models.Tipo", b =>
                {
                    b.HasOne("SGContrato.Models.Seccion", "Seccion")
                        .WithMany("Tipos")
                        .HasForeignKey("seccionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
